#!/usr/bin/env bash

[ -n "$ZSH_VERSION" ] && zmodload zsh/datetime
_KRIOGENX_RC_START=$EPOCHREALTIME

# Kriogenx Scripts
# FOR ZSH AND BASH
# scripts.kriogenx.net

####################
# SETTINGS

export KRIOGENX_DIR=~/.kriogenx
export KRIOGENX_RC="$KRIOGENX_DIR"/configs/bashrc
export USER_RC=~/Dropbox/Office/settings/bashrc

####################
# ENVIRONMENT VARIABLES

# Homebrew GCC
: '
if ! type CC >/dev/null; then
  if [[  -e /usr/local/bin/gcc-4.2 ]]; then
    export CC=/usr/local/bin/gcc-4.2
  elif [[ -e /usr/bin/gcc-4.2 ]]; then
    export CC=/usr/bin/gcc-4.2
  elif [[ `which gcc` =~ "not found" ]]; then
    export CC=`which gcc`
  fi
fi
'
# export CPPFLAGS=-I/opt/X11/include

# Postgres
# if [[ -e /usr/local/var/postgres ]]; then
#   export PGDATA=/usr/local/var/postgres
# fi

####################
# PATH CHANGES

# Homebrew Git
[[ -d /usr/local/git/bin && ! $PATH =~ '/usr/local/git/bin' ]] && export PATH=/usr/local/git/bin:$PATH

# Homebrew Bin
export PATH=${PATH//:\/usr\/local\/bin/}
[[ ! $PATH =~ '/usr/local/bin' ]] && export PATH=/usr/local/bin:$PATH
[[ ! $PATH =~ '/usr/local/sbin' ]] && export PATH=/usr/local/sbin:$PATH

append_path()
{
  [[ -e $1 ]] && [[ ! $PATH =~ $1 ]] && export PATH="$PATH":$1
}

# User Bin
append_path $HOME/bin

# RVM Bin
append_path $HOME/.rvm/bin

# RVM Gem Error
#export GEM_BASE=${GEM_HOME//@[a-zA-Z0-9]*/}
#[[ $GEM_BASE != $GEM_HOME && -d $GEM_BASE/bin ]] && export PATH=$GEM_BASE/bin:$PATH

# RVM Load Gem Bin
append_path $GEM_HOME/bin

# Apple Command Line
append_path /Developer/usr/bin

# MySQL Native Install
append_path /usr/local/mysql/support-files
append_path /usr/local/mysql/bin

# Kriogenx Bin
append_path "$KRIOGENX_DIR"/bin

# Xcode Developer
append_path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
append_path /Applications/Xcode.app/Contents/Developer/usr/bin

# RVM SETTINGS
RVM_SCRIPT=~/.rvm/scripts/rvm
if [[ -f $RVM_SCRIPT ]] && type rvm >/dev/null 2>&1; then
  export rvm_trust_rvmrcs_flag=1
  export rvm_project_rvmrc_default=1
  export rvm_auto_reload_flag=2

  source $RVM_SCRIPT
fi


####################
# PIMP MY SHELL

source "$KRIOGENX_DIR"/configs/rc/pimpmyshellrc

####################
# ALIASES

source "$KRIOGENX_DIR"/configs/rc/aliasesrc

[[ -e "$USER_RC" ]] && source "$USER_RC"

awk -v s="$_KRIOGENX_RC_START" -v e="$EPOCHREALTIME" 'BEGIN{printf "Kriogenx bashrc loaded in %.0fms\n", (e-s)*1000}'
unset _KRIOGENX_RC_START
